### PR TITLE
Encode file URL

### PR DESCRIPTION
**Pull request by DFranzen**
This fixes the problem with umlauts in the file url and probably a bunch more with other characters

### CODE REVIEW

**Comment by m0ngr31** [comment]
Can you confirm that this works for you?

**Comment by DFranzen** [comment]
I did not set up https for my test (and therefore could not test with
alexa directly), but with the ssl part disabled the test with a local
server was able to download the file containing the characters in question

**Comment by jingai** [comment]
It should be tested with Alexa too though.. I seem to remember the Echo does some encoding on its own too.

**Comment by DFranzen** [comment]
Just set up my changes in heroku and the proxy works like a charm with
https and Alexa.

Howerever, it seems the Kodi JSON interface has an encoding bug, too.
The command "AudioLibrary.GetSongDetails" returns miss-encoded umlauts
in the path. Your version of the kodi-alexa skill should be fine though,
since you are only using "AudioLibrary.GetSongs", which is uneffected by
the bug. (And the only effects the paths that were not working with the
current version of the proxy anyway). Just in case you change it in the
future.

Greetings from Berlin
Daniel

**Pull request merged**
